### ISSUE TITLE
Problems with HTML tags

### ISSUE THREAD

**Issue by mambax7** [GregMage/xmfaq#2]
Problems with HTML tags:

![image](https://cloud.githubusercontent.com/assets/613686/17075701/fe6c92ec-5069-11e6-9222-754ff58c69a7.png)

**Comment by mambax7** [comment]
The fix:  add in /class/xmfaq_question.php in the __construct:

``` php
        $this->initVar('dohtml', XOBJ_DTYPE_INT, 1, false);
```

**Comment by GregMage** [comment]
Thanks for your modifications
